/**
 * StoreCashFlow.Api
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * DTO для создания клиента
 */
export interface CustomerCreateDTO {
    /**
     * Номер карты
     */
    cardNumber: string;
    /**
     * Фамилия
     */
    lastName?: string | null;
    /**
     * Имя
     */
    firstName?: string | null;
    /**
     * Отчество
     */
    patronymic?: string | null;
}

