/**
 * StoreCashFlow.Api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Product } from './product';
import { Store } from './store';


/**
 * DTO для информации о просроченном товаре
 */
export interface ExpiredProductInfoDto { 
    product?: Product;
    store?: Store;
}

