/**
 * StoreCashFlow.Api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * DTO для высоких продаж
 */
export interface HighSalesDto { 
    /**
     * Идентификатор магазина
     */
    storeId?: number;
    /**
     * Указанная сумма продаж
     */
    totalSales?: number;
}

