/**
 * StoreCashFlow.Api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Product } from './product';
import { Store } from './store';


export interface ProductAvailability { 
    id?: number;
    store: Store;
    product: Product;
    quantity: number;
}

