/**
 * StoreCashFlow.Api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * DTO для создания информации о наличии товара
 */
export interface ProductAvailabilityCreateDTO { 
    /**
     * Магазин
     */
    storeId?: number;
    /**
     * Товар
     */
    productId?: string | null;
    /**
     * Количество
     */
    quantity?: number;
}

