/**
 * StoreCashFlow.Api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * DTO для информации о средней стоимости товарной группы в магазине
 */
export interface ProductPriceInfoDto { 
    /**
     * Идентификатор магазина
     */
    storeId?: number;
    /**
     * Товарная группа
     */
    productGroupCode?: string | null;
    /**
     * Средняя цена
     */
    avgPrice?: number;
}

