/**
 * StoreCashFlow.Api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ProductType } from './productType';


export interface Product { 
    barcode: string;
    productGroupCode: string;
    name: string;
    weight: number;
    productType: ProductType;
    price: number;
    expirationDate: string;
}

