/**
 * StoreCashFlow.Api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * DTO для создания товара
 */
export interface ProductCreateDTO { 
    /**
     * Штрих-код
     */
    barcode?: string | null;
    /**
     * Код товарной группы
     */
    productGroupCode?: string | null;
    /**
     * Наименование
     */
    name?: string | null;
    /**
     * Вес упаковки
     */
    weight?: number;
    /**
     * Тип (штучный, развесной)
     */
    productTypeId?: number;
    /**
     * Стоимость
     */
    price?: number;
    /**
     * Предельную дату хранения
     */
    expirationDate?: string;
}

