/**
 * StoreCashFlow.Api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * DTO для создания типа товара
 */
export interface ProductTypeCreateDTO { 
    /**
     * Тип товара
     */
    name?: string | null;
}

