/**
 * StoreCashFlow.Api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * DTO для продажи
 */
export interface SaleDTO { 
    /**
     * Идентификатор покупки
     */
    saleId?: number;
    /**
     * Магазин
     */
    storeId?: number;
    /**
     * Продукт
     */
    productId?: string | null;
    /**
     * Количество
     */
    quantity?: number;
    /**
     * Дата продажи
     */
    saleDate?: string;
    /**
     * Покупатель
     */
    customerId?: number;
}

