/**
 * StoreCashFlow.Api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Customer } from './customer';
import { Product } from './product';
import { Store } from './store';


export interface Sale { 
    saleId?: number;
    store: Store;
    product: Product;
    quantity: number;
    saleDate: string;
    customer: Customer;
}

