/**
 * StoreCashFlow.Api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * DTO для информации о продажах
 */
export interface SaleInfoDto { 
    /**
     * Название продукта
     */
    productName?: string | null;
    /**
     * Общая сумма продаж
     */
    totalAmount?: number;
}

