/**
 * StoreCashFlow.Api
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * DTO для создания магазина
 */
export interface StoreCreateDTO { 
    /**
     * Местоположение магазина
     */
    location?: string | null;
}

